services:
  - type: web
    name: lovely-locs-booking
    runtime: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /healthz
    envVars:
      - fromGroup: env. var updates 06/01/26
